# Generated by Django 3.1 on 2021-01-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0004_auto_20210121_1308"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="text",
            field=models.TextField(blank=True, default=None),
        ),
    ]
