# Generated by Django 3.1 on 2021-01-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0005_note_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
