# Generated by Django 3.1 on 2021-02-04 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0007_auto_20210203_2234"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={"ordering": ["date_created"]},
        ),
    ]
